### ISSUE TITLE
JSON request error

### ISSUE THREAD

**Issue by EV3REST** [LuqueDaniel/pybooru#25]
Cannot parse data from Yande.re
`<telegram.utils.promise.Promise object at 0x7fa70014ebe0>`
`'In _json_request: 404, Not Found - Not found -- URL: https://yande.re/post.json'`

**Comment by MadiNyan** [comment]
Try opening the `pybooru/resources.py` and change the `https` to `http` for yandere in `site_list` section.
This worked for me.

**Comment by LuqueDaniel** [comment]
I'll check it soon.

**Comment by LuqueDaniel** [comment]
Develop versión (next version):
`{'status': 'OK, Request was successful', 'status_code': 200, 'url': 'https://yande.re/post.json'}`

**Comment by EV3REST** [comment]
Thanks for the replies, everything works fine after MadiNyan's solution, will try updating to Develop version soon!
