### ISSUE TITLE
Make documentation

### ISSUE THREAD

**Issue by LuqueDaniel** [LuqueDaniel/pybooru#26]
Create documentation for Pybooru. With Sphinx and Read the Docs.

**Comment by LuqueDaniel** [comment]
Done

**Comment by EV3REST** [comment]
http://pybooru.readthedocs.io/en/stable/ is not working for some reason.

**Comment by LuqueDaniel** [comment]
My bad, try now :)

**Comment by EV3REST** [comment]
Works now, but the links for examples still guide to the `develop` tree
