### ISSUE TITLE
feature_add(post_id) not working

### ISSUE THREAD

**Issue by ddjmw88** [LuqueDaniel/pybooru#42]
I am running a function similar to the below after obtaining a post from client.post_list().
I've made sure that the post_id being passed is valid, and the login auth appears to be fine since other functions like favorites_list() work as expected
```
client = Danbooru('danbooru', username=API_USER, api_key=API_KEY)
def favoriteId(post_id):
    client.favorite_add(post_id)
```
However, nothing appears to happen and the post is not added to favorites.

**Comment by LuqueDaniel** [comment]
I'll goint to test

**Comment by LuqueDaniel** [comment]
@ddjmw88 It's because the url of danbooru included in Pybooru isn't HTTPS (I have to fix it).

**Solution:**
```python
client = Danbooru(site_url='https://danbooru.donmai.us', username=API_USER, api_key=API_KEY)
def favoriteId(post_id):
    client.favorite_add(post_id)
```
`site_url='https://danbooru.donmai.us'`.

Let's me know if this solve (or not) your issue.

**Comment by ddjmw88** [comment]
> @ddjmw88 It's because the url of danbooru included in Pybooru isn't HTTPS (I have to fix it).
> 
> **Solution:**
> 
> ```python
> client = Danbooru(site_url='https://danbooru.donmai.us', username=API_USER, api_key=API_KEY)
> def favoriteId(post_id):
>     client.favorite_add(post_id)
> ```
> 
> `site_url='https://danbooru.donmai.us'`.
> 
> Let's me know if this solve (or not) your issue.

This fixed it! Thank you for the help. Do you think you could add a note of this to the documentation?

**Comment by LuqueDaniel** [comment]
In the next version of Pybooru, all URLs will be HTTPS.
