### ISSUE TITLE
I cant add more then 1 tag

### ISSUE THREAD

**Issue by Ganoosh** [LuqueDaniel/pybooru#43]
Ive been trying to add multiple tags for danbooru and I figured it was one of the following:
`tags='tag1 tag2'`
`tags='tag1', 'tag2'`
`tags=["tag1", "tag2"]`
Which it was none of, im greatly confused on this issue and any information would help.

Along with that this one is more simple, but I have no clue on how to declare the site name for moebooru.

Actually, nvm it was just the tag I was using but why doesnt it work?

**Comment by LuqueDaniel** [comment]
@Ganoosh Tags must be provided as follows

```python
posts = client.post_list(tags='blue_eyes red_hair')
```

Moebooru / Danbooru `site_name` parameter, is the first parameter of the classes.

```python
cliente = Moebooru('konachan')
# or the same
client2 = Moebooru(site_name='konachan')
```
